- name: update go
  connection: local
  hosts: localhost
  vars:
    home: 
    version: 1.14.2
    source: "https://dl.google.com/go/go{{ version }}.linux-amd64.tar.gz"
    sha256sum: 6272d6e940ecb71ea5636ddb5fab3933e087c1356173c61f4a803895e947ebb3
  tasks:
  - name: remove old go install
    file:
      path: "{{ ansible_env.HOME }}/.local/go/"
      state: absent

  - name: download and set up new go
    unarchive:
      src: "{{ source }}"
      dest: "{{ ansible_env.HOME }}/.local/"
      remote_src: yes
  
  - name: print new go version
    command: go version
    register: output

  - debug:
      msg: "{{ output.stdout }}"

  - name: update coding tools via neovim
    command: nvim +GoUpdateBinaries +qa --headless
